version: "3.7"

x-app:
  &app
  build: .
  volumes:
    - "site_packages:/usr/local/lib/python3.7/site-packages"
    - "local_bin:/usr/local/bin"
    - "./:/code"
  depends_on:
    - db
    - rabbit
  env_file:
    - .env

services:
  web:
    <<: *app
    ports:
      - "8000:8000"
  celery:
    <<: *app
    command: "celery -A ${PROJECT_NAME} worker -l info"
  rabbit:
    image: rabbitmq
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  email:
    image: python:3.7-alpine
    command: "python -m smtpd -c DebuggingServer -n 0.0.0.0:${EMAIL_PORT}"
    env_file:
      - .env

  mongo:
    image: mongo:3
    volumes:
      - mongo:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  graylog:
    image: graylog/graylog:3.1
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes:
  postgres_data:
  local_bin:
  site_packages:
  mongo:
  es_data:
  graylog_journal:
